
% Objective ----------------------------------------------
% if stochastic
%     [prob.Objective, prob.Constraints] =...
%         problemSetup2(threshold,switchcount,V_extmeas,G,SoC,SoCest_temp,...
%         I,Ieff,Iref*uncertainty_factor,Iprev,Gprev,Vref,vmeas,OCVest_temp,R0est_temp,...
%         v1est_temp,v2est_temp,CCCV,dQAh_pref);
% else
    [prob.Objective, prob.Constraints] =...
        problemSetup(threshold,switchcount,V_extmeas,G,SoC,SoCest_temp,...
        I,Ieff,Iref*uncertainty_factor,Iprev,Gprev,Vref,vmeas,OCVest_temp,R0est_temp,...
        v1est_temp,v2est_temp,CCCV,dQAh_pref,v1,v2,v1eff,v2eff);
% end
% Solution -----------------------------------------------
[sol,~,exitflag] = solve(prob,'Options',options);
disp(exitflag)
disp('----------------------------------------------------')